package Diagram;

public enum TypeNeterminal {
    S,
    MNOGO_OPISANIA,
    DATA,
    LIST,
    LIST_PLUS,
    ASSIGN,
    ARRAY_OR_NEW_ARRAY,
    FUNCTION,
    OPERATORS_AND_OPISANIA_IN_CURCLY_BRACE,
    OPERATORS_AND_DATA,
    OPERATOR,
    ASSIGN_FUNCTION_ELEMENT,
    EXPRESSION_OR_NEW_ARRAY,
    ARRAY,

    EXPRESSION,
    EXPRESSION_PLUS,
    EXPRESSION2,
    EXPRESSION2_PLUS,
    EXPRESSION3,
    EXPRESSION3_PLUS,
    EXPRESSION4,
    EXPRESSION4_PLUS,
    EXPRESSION5,
    EXPRESSION6,
    PEREMENNAY_ELEMENT
}
